### ISSUE TITLE
Objects-lab #4 allowed me to submit an incorrect answer

### ISSUE THREAD

**Issue by ryanSherry** [learn-co-curriculum/javascript-objects-lab#14] opened 2017-05-17 15:09 UTC
I was able to pass the 4th part of the lab with the following incorrect code:

`function deleteFromObjectByKey(object,key) {
  return Object.assign({},object,{});
}`

After submitting it, I immediately realized it was incorrect and corrected the code then resubmitted:

`function deleteFromObjectByKey(object,key) {
  var newObj = Object.assign({},object);
  delete newObj[key];
  return object;
}`

It looks like the test is just looking to see if the object is returned with the same key and value so that's why the first function I wrote worked. 

There needs to be some sort of validation to make sure that people are creating a new object via Object.assign, deleting the value from the new object and then returning the original object that was passed into the function.

**Comment by Chovin** [comment] 2018-08-25 01:08
I was not able to reproduce this. Using the solution you mentioned was incorrect, I get the following

```
  1) Objects deleteFromObjectByKey(object, key) deletes `key` from a clone of object and returns the new
 object (it is non-destructive):
     Error: Expected 1 to be undefined
```

I believe this test catches this https://github.com/learn-co-curriculum/javascript-objects-lab/blob/c36807843357d797e30d7b24b0b57066e638c814/test/index-test.js#L60-L64

**Comment by drakeltheryuujin** [comment] 2018-10-05 17:36
Hi there,

I'm having difficulty reproducing the issue with your solution, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by drakeltheryuujin** 2018-10-05 17:36 UTC
Labels: Curriculum
